=== api-evangelist/cloudwatch/json-schema/cloudwatch-putcompositealarminput-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "#/components/schemas/PutCompositeAlarmInput",
  "title": "PutCompositeAlarmInput",
  "type": "object",
  "required": [
    "AlarmName",
    "AlarmRule"
  ],
  "properties": {
    "AlarmName": {
      "type": "string",
      "minLength": 1,
      "maxLength": 255,
      "description": "The name for the composite alarm.",
      "example": "example_value"
    },
    "AlarmDescription": {
      "type": "string",
      "maxLength": 1024,
      "description": "The description for the composite alarm.",
      "example": "example_value"
    },
    "ActionsEnabled": {
      "type": "boolean",
      "description": "Indicates whether actions should be executed during any changes to the alarm state.",
      "example": true
    },
    "AlarmActions": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "maxItems": 5,
      "description": "The actions to execute when this alarm transitions to the ALARM state.",
      "example": []
    },
    "AlarmRule": {
      "type": "string",
      "minLength": 1,
      "maxLength": 10240,
      "description": "An expression that specifies which other alarms are to be evaluated to determine this composite alarm's state.",
      "example": "example_value"
    },
    "InsufficientDataActions": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "maxItems": 5,
      "description": "The actions to execute when this alarm transitions to the INSUFFICIENT_DATA state.",
      "example": []
    },
    "OKActions": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "maxItems": 5,
      "description": "The actions to execute when this alarm transitions to the OK state.",
      "example": []
    },
    "Tags": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/Tag"
      },
      "description": "A list of key-value pairs to associate with the composite alarm.",
      "example": []
    },
    "ActionsSuppressor": {
      "type": "string",
      "description": "Actions will be suppressed if the suppressor alarm is in the ALARM state.",
      "example": "example_value"
    },
    "ActionsSuppressorWaitPeriod": {
      "type": "integer",
      "description": "The maximum time in seconds that the composite alarm waits for the suppressor to go into ALARM state.",
      "example": 10
    },
    "ActionsSuppressorExtensionPeriod": {
      "type": "integer",
      "description": "The maximum time in seconds that the composite alarm waits after the suppressor leaves the ALARM state.",
      "example": 10
    }
  }
}

=== api-evangelist/cloudwatch/examples/cloudwatch-put-composite-alarm-input-example.json
{
  "AlarmName": "example_value",
  "AlarmDescription": "example_value",
  "ActionsEnabled": true,
  "AlarmActions": [],
  "AlarmRule": "example_value",
  "InsufficientDataActions": [],
  "OKActions": [],
  "Tags": [],
  "ActionsSuppressor": "example_value",
  "ActionsSuppressorWaitPeriod": 10,
  "ActionsSuppressorExtensionPeriod": 10
}
